filter:
    paths: ["src/*"]
    excluded_paths: ["vendor/*", "tests/*", "resources/", "public/"]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage: false

build:
    environment:
        php: 7.2
        mysql: 5.7
        node: v10.14.2
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
            before:
                 - composer self-update
                 - composer update --no-interaction --prefer-dist --no-progress
                 - mysql -u root -e "CREATE DATABASE IF NOT EXISTS slim_skeleton_int CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
                 - npm install
                 - npm run build
    tests:
        before:
            -
                command: composer test-coverage
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'
