language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-progress
  - mysql -e 'CREATE DATABASE IF NOT EXISTS slim_skeleton_int CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - cp config/env.example.php config/env.php
  - cd $TRAVIS_BUILD_DIR

script:
  - composer migrate
  - composer check-all
